ta404:
  database:
    mybatis:
      datasourceList: ta404ds
      ta404ds:
        datasourceType: druid #druid, localJndi, weblogicJndi
        page-dialect: mysql  #分页方言oracle,mysql,postgresql,sqlserver,informix,dm
        url: jdbc:mysql://127.0.0.1:3306/ta404?serverTimezone=UTC
        username: root
        password: guanhe
        driverClassName: com.mysql.jdbc.Driver
        minIdle: 5
        mappers:
          - com.yinhai.ta404.module.mybatis.mapper
          - com.yinhai.ta404.module.**.mapper.read
          - com.yinhai.ta404.module.**.mapper.write
          - com.yinhai.ta404.component.**.mapper.read
          - com.yinhai.ta404.component.**.mapper.write
        type-aliases-package:
          - com.yinhai.ta404.component.**.entity
        mapper-locations:
          - classpath*:mapper/read/*.xml
          - classpath*:mapper/write/*.xml
        transaction: #用于扩展事务管理器属性
          enforceReadOnly: false #表示DataSourceTrasactionManager支持只读事务，某些数据库不支持此属性，需要关闭
      # sqlsessionfactory: #用于扩展sqlSessionFactory属性
